display_name: Docan
package_name: docan
maintainer:
  name: OpenLyst
  email: contact@openlyst.com
priority: optional
section: utils
essential: false
installed_size: 50000
icon: linux/data/icons/hicolor/512x512/apps/docan.png
keywords:
  - ai
  - chat
  - gemini
categories:
  - Utility
startup_notify: true
